FROM handcraftedbits/pgmodeler-builder-cc
MAINTAINER HandcraftedBits <opensource@handcraftedbits.com>

RUN cd /opt/mxe && \
  make MXE_TARGETS='x86_64-w64-mingw32.shared x86_64-w64-mingw32.static' zlib && \
  make MXE_TARGETS='x86_64-w64-mingw32.shared' cc dbus openssl pcre2 fontconfig freetype harfbuzz jpeg libpng zlib zstd \
    sqlite mesa postgresql libxml2 && \
  mkdir -p /opt/src && \
  cd /opt/src && \
  git clone https://github.com/digitalist/pydeployqt.git

